# locals {
#   custom_constraint_names = toset([
#     "custom.cloudbuildDisableWorkerPoolExternalIP",
#     "custom.cloudkmsAllowedRotationPeriod",
#     "custom.cloudrunDisableEnvironmentVariablePattern",
#     # "custom.cloudsqlDisableExternalIP",
#     "custom.cloudsqlDisablePublicAuthorizedNetworks",
#     "custom.cloudsqlEnforcePasswordComplexity",
#     "custom.cloudsqlRequireAutomatedBackup",
#     "custom.cloudsqlRequireMySQLDatabaseFlags",
#     "custom.cloudsqlRequirePointInTimeRecovery",
#     "custom.cloudsqlRequirePostgreSQLDatabaseFlags",
#     "custom.cloudsqlRequireRootPassword",
#     "custom.cloudsqlRequireSQLServerDatabaseFlags",
#     "custom.cloudsqlRequireSSLConnection",
#     "custom.computeDisableIPForwarding",
#     "custom.dataprocRequireDiskCmekEncryption",
#     "custom.dnsAllowedSigningAlgorithms",
#     "custom.dnsRequireManageZoneDNSSEC",
#     "custom.dnsRequirePolicyLogging",
#     "custom.firewallRestrictOpenWorldRule",
#     "custom.firewallRestrictRdpPolicyRule",
#     "custom.firewallRestrictRdpRule",
#     "custom.firewallRestrictSshPolicyRule",
#     "custom.firewallRestrictSshRule",
#     "custom.gkeAllowedInitialClusterVersions",
#     "custom.gkeAllowedNodePoolImages",
#     "custom.gkeAllowedReleaseChannels",
#     "custom.gkeDisableAlphaCluster",
#     "custom.gkeDisableClientCertificateAuthentication",
#     "custom.gkeDisableKubernetesDashboard",
#     "custom.gkeDisableLegacyAbac",
#     "custom.gkeDisableLegacyMetadataEndpoints",
#     "custom.gkeDisableNodePoolDefaultServiceAccount",
#     "custom.gkeRequireBinaryAuthorization",
#     "custom.gkeRequireConfidentialNodes",
#     "custom.gkeRequireCOSImage",
#     "custom.gkeRequireDatabaseEncryption",
#     "custom.gkeRequireDataplaneV2",
#     "custom.gkeRequireGKEMetadataServer",
#     "custom.gkeRequireGroupsRBAC",
#     "custom.gkeRequireIntegrityMonitoring",
#     "custom.gkeRequireIntraNodeVisibility",
#     "custom.gkeRequireLogging",
#     "custom.gkeRequireMasterAuthorizedNetworks",
#     "custom.gkeRequireMonitoring",
#     "custom.gkeRequireNetworkPolicy",
#     "custom.gkeRequireNodePoolAutoRepair",
#     "custom.gkeRequireNodePoolAutoUpgrade",
#     "custom.gkeRequireNodePoolCMEKEncryption",
#     "custom.gkeRequireNodePoolSandbox",
#     "custom.gkeRequirePrivateEndpoint",
#     "custom.gkeRequirePrivateNodes",
#     "custom.gkeRequireRegionalClusters",
#     "custom.gkeRequireSecureBoot",
#     "custom.gkeRequireShieldedNodes",
#     "custom.gkeRequireVPCNativeCluster",
#     "custom.gkeRequireWorkloadIdentity",
#     "custom.iamAllowedMembers",
#     "custom.iamDisableAdminServiceAccount",
#     "custom.iamDisableBasicRoles",
#     "custom.iamDisableProjectServiceAccountImpersonationRoles",
#     "custom.iamDisablePublicBindings",
#     "custom.networkDisableTargetHTTPProxy",
#     "custom.networkDisableWeakSSLPolicy",
#     "custom.networkRequireBackendServiceLogging",
#     "custom.networkRequireCustomModeVpc",
#     "custom.networkRequireSubnetPrivateGoogleAccess",
#     "custom.networkRequireVPCFlowLogs"
#   ])
#     org_id = "262782368104"
# }

# import {
#   for_each = local.custom_constraint_names
#   id = "organizations/${local.org_id}/customConstraints/${each.key}"
#   to = module.organization.google_org_policy_custom_constraint.constraint[each.key]
# }